CREATE TABLE post_event_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    night_start_utc TIMESTAMPTZ NOT NULL,
    schema_version INT NOT NULL DEFAULT 1,
    status TEXT NOT NULL CHECK (status IN ('READY', 'FAILED')),
    payload_json JSONB NOT NULL,
    error_code TEXT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    -- Keep schema_version in unique key to support parallel storage of multiple payload schema versions for one night.
    CONSTRAINT uq_post_event_stories_club_night_schema UNIQUE (club_id, night_start_utc, schema_version)
);

CREATE INDEX idx_post_event_stories_club_night_desc
    ON post_event_stories(club_id, night_start_utc DESC);
CREATE INDEX idx_post_event_stories_club_generated_desc
    ON post_event_stories(club_id, generated_at DESC);

CREATE TABLE guest_segments (
    club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    window_days INT NOT NULL CHECK (window_days > 0),
    segment_type TEXT NOT NULL CHECK (segment_type IN ('NEW', 'FREQUENT', 'SLEEPING')),
    computed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_guest_segments PRIMARY KEY (club_id, user_id, window_days)
);

CREATE INDEX idx_guest_segments_club_window_segment
    ON guest_segments(club_id, window_days, segment_type);
