CREATE TABLE hall_plans (
    hall_id BIGINT PRIMARY KEY REFERENCES halls(id) ON DELETE CASCADE,
    bytes BYTEA NOT NULL,
    content_type TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
