ALTER TABLE users ADD COLUMN IF NOT EXISTS encrypted_phone TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_hash VARCHAR(64) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS anonymized_at TIMESTAMP WITH TIME ZONE NULL;
CREATE INDEX IF NOT EXISTS idx_users_phone_hash ON users(phone_hash);

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS encrypted_phone TEXT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS phone_hash VARCHAR(64) NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS anonymized_at TIMESTAMP WITH TIME ZONE NULL;
CREATE INDEX IF NOT EXISTS idx_bookings_phone_hash ON bookings(phone_hash);

ALTER TABLE guest_list_entries ADD COLUMN IF NOT EXISTS encrypted_phone TEXT NULL;
ALTER TABLE guest_list_entries ADD COLUMN IF NOT EXISTS phone_hash VARCHAR(64) NULL;
ALTER TABLE guest_list_entries ADD COLUMN IF NOT EXISTS anonymized_at TIMESTAMP WITH TIME ZONE NULL;
CREATE INDEX IF NOT EXISTS idx_guest_list_entries_phone_hash ON guest_list_entries(phone_hash);

CREATE TABLE IF NOT EXISTS privacy_retention_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_user_id BIGINT NULL,
    mode TEXT NOT NULL,
    details_json TEXT NOT NULL
);
