ALTER TABLE music_items
    ADD COLUMN description TEXT NULL;

ALTER TABLE music_items
    ADD COLUMN item_type TEXT NOT NULL DEFAULT 'TRACK';

ALTER TABLE music_items
    ADD COLUMN audio_asset_id BIGINT NULL;

ALTER TABLE music_items
    ADD COLUMN cover_asset_id BIGINT NULL;

CREATE TABLE music_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    bytes BYTEA NOT NULL,
    content_type TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE music_items
    ADD CONSTRAINT fk_music_items_audio_asset
        FOREIGN KEY (audio_asset_id) REFERENCES music_assets(id) ON DELETE SET NULL;

ALTER TABLE music_items
    ADD CONSTRAINT fk_music_items_cover_asset
        FOREIGN KEY (cover_asset_id) REFERENCES music_assets(id) ON DELETE SET NULL;

CREATE INDEX idx_music_items_type_published
    ON music_items(item_type, published_at DESC);
