-- Battle scope: club-scoped (club_id nullable for global catalog compatibility), lookup APIs always filter by club_id.
CREATE TABLE IF NOT EXISTS music_battles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NULL,
    item_a_id BIGINT NOT NULL,
    item_b_id BIGINT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'CLOSED')),
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT fk_music_battles_club FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE SET NULL,
    CONSTRAINT fk_music_battles_item_a FOREIGN KEY (item_a_id) REFERENCES music_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_music_battles_item_b FOREIGN KEY (item_b_id) REFERENCES music_items(id) ON DELETE CASCADE,
    CONSTRAINT chk_music_battles_items_distinct CHECK (item_a_id <> item_b_id),
    CONSTRAINT chk_music_battles_time_range CHECK (starts_at < ends_at)
);

CREATE INDEX IF NOT EXISTS idx_music_battles_scope_active_lookup
    ON music_battles(club_id, status, starts_at DESC, ends_at, id DESC);

CREATE INDEX IF NOT EXISTS idx_music_battles_scope_recent
    ON music_battles(club_id, starts_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS music_battle_votes (
    battle_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    chosen_item_id BIGINT NOT NULL,
    voted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT pk_music_battle_votes PRIMARY KEY (battle_id, user_id),
    CONSTRAINT fk_music_battle_votes_battle FOREIGN KEY (battle_id) REFERENCES music_battles(id) ON DELETE CASCADE,
    CONSTRAINT fk_music_battle_votes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_music_battle_votes_item FOREIGN KEY (chosen_item_id) REFERENCES music_items(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_music_battle_votes_battle_item
    ON music_battle_votes(battle_id, chosen_item_id);

CREATE TABLE IF NOT EXISTS music_item_stems_assets (
    item_id BIGINT PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT fk_music_item_stems_item FOREIGN KEY (item_id) REFERENCES music_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_music_item_stems_asset FOREIGN KEY (asset_id) REFERENCES music_assets(id) ON DELETE CASCADE
);
