CREATE TABLE IF NOT EXISTS telegram_webhook_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_id BIGINT NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    payload_json CLOB NOT NULL,
    status VARCHAR(16) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_error CLOB,
    processed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_telegram_webhook_updates_update_id UNIQUE (update_id)
);

CREATE INDEX IF NOT EXISTS idx_telegram_webhook_updates_status_next_attempt
    ON telegram_webhook_updates (status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_telegram_webhook_updates_received_at
    ON telegram_webhook_updates (received_at);
