CREATE TABLE IF NOT EXISTS table_deposit_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deposit_id BIGINT NOT NULL REFERENCES table_deposits(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES table_sessions(id) ON DELETE CASCADE,
    club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    night_start_utc TIMESTAMP WITH TIME ZONE NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('INITIAL','TOPUP','SECURITY','ADJUSTMENT')),
    amount_minor BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_id BIGINT NOT NULL REFERENCES users(id),
    reason TEXT NULL,
    payment_id UUID NULL REFERENCES payments(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_table_deposit_operations_deposit
    ON table_deposit_operations (deposit_id, id);

CREATE INDEX IF NOT EXISTS idx_table_deposit_operations_club_night
    ON table_deposit_operations (club_id, night_start_utc);

CREATE INDEX IF NOT EXISTS idx_table_deposit_operations_payment
    ON table_deposit_operations (payment_id);

CREATE TABLE IF NOT EXISTS table_deposit_operation_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL REFERENCES table_deposit_operations(id) ON DELETE CASCADE,
    category_code TEXT NOT NULL,
    amount_minor BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_table_deposit_operation_allocations_operation
    ON table_deposit_operation_allocations (operation_id);

INSERT INTO table_deposit_operations (
    deposit_id,
    session_id,
    club_id,
    night_start_utc,
    type,
    amount_minor,
    created_at,
    actor_id,
    reason,
    payment_id
)
SELECT
    td.id,
    td.table_session_id,
    td.club_id,
    td.night_start_utc,
    'INITIAL',
    td.amount_minor,
    td.created_at,
    td.created_by,
    NULL,
    td.payment_id
FROM table_deposits td
WHERE NOT EXISTS (
    SELECT 1
    FROM table_deposit_operations tdo
    WHERE tdo.deposit_id = td.id
);

INSERT INTO table_deposit_operation_allocations (operation_id, category_code, amount_minor)
SELECT
    tdo.id,
    tda.category_code,
    tda.amount_minor
FROM table_deposit_operations tdo
JOIN table_deposit_allocations tda ON tda.deposit_id = tdo.deposit_id
WHERE tdo.type = 'INITIAL'
  AND NOT EXISTS (
      SELECT 1
      FROM table_deposit_operation_allocations tdoa
      WHERE tdoa.operation_id = tdo.id
  );
