ALTER TABLE booking_outbox ADD COLUMN IF NOT EXISTS lease_until TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE booking_outbox ADD COLUMN IF NOT EXISTS lease_owner TEXT NULL;
CREATE INDEX IF NOT EXISTS idx_booking_outbox_lease_until ON booking_outbox(lease_until);

ALTER TABLE notify_campaigns ADD COLUMN IF NOT EXISTS text TEXT NOT NULL DEFAULT '';
ALTER TABLE notify_campaigns ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS notify_campaign_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES notify_campaigns(id) ON DELETE CASCADE,
    audit_action TEXT NOT NULL,
    actor TEXT NOT NULL,
    reason TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notify_campaign_audit_campaign_id
    ON notify_campaign_audit(campaign_id, created_at DESC);
