CREATE TABLE analytics_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    night_start_utc TIMESTAMP WITH TIME ZONE NOT NULL,
    window_days INT NOT NULL CHECK (window_days > 0),
    schema_version INT NOT NULL DEFAULT 1,
    status TEXT NOT NULL CHECK (status IN ('READY', 'FAILED')),
    payload_json CLOB NOT NULL,
    error_code TEXT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_analytics_snapshots_club_night_window_schema UNIQUE (club_id, night_start_utc, window_days, schema_version)
);

CREATE INDEX idx_analytics_snapshots_lookup
    ON analytics_snapshots(club_id, night_start_utc, window_days, schema_version);
