ALTER TABLE payment_actions ADD COLUMN refund_fingerprint_version INTEGER;
ALTER TABLE payment_actions ADD COLUMN refund_request_mode VARCHAR(32);
ALTER TABLE payment_actions ADD COLUMN refund_request_amount_minor BIGINT;
ALTER TABLE payment_actions ADD COLUMN refund_result_amount_minor BIGINT;
ALTER TABLE payment_actions ADD COLUMN refund_source_kind VARCHAR(32);

ALTER TABLE payment_actions
    ADD CONSTRAINT payment_actions_refund_fingerprint_check
    CHECK (
        CASE
            WHEN refund_fingerprint_version IS NULL THEN
                refund_request_mode IS NULL
                AND refund_request_amount_minor IS NULL
            WHEN action = 'REFUND'
                AND refund_fingerprint_version = 1
                AND refund_request_mode = 'EXPLICIT'
                THEN refund_request_amount_minor IS NOT NULL
                    AND refund_request_amount_minor >= 0
            WHEN action = 'REFUND'
                AND refund_fingerprint_version = 1
                AND refund_request_mode = 'ALL_REMAINING'
                THEN refund_request_amount_minor IS NULL
            ELSE FALSE
        END
    );

ALTER TABLE payment_actions
    ADD CONSTRAINT payment_actions_refund_result_amount_check
    CHECK (
        refund_result_amount_minor IS NULL
        OR (
            action = 'REFUND'
            AND status = 'OK'
            AND refund_result_amount_minor >= 0
        )
    );

ALTER TABLE payment_actions
    ADD CONSTRAINT payment_actions_refund_source_kind_check
    CHECK (
        CASE
            WHEN refund_source_kind IS NULL THEN
                refund_result_amount_minor IS NULL
                OR refund_result_amount_minor = 0
            WHEN refund_source_kind = 'ATOMIC_ACTION' THEN
                action = 'REFUND'
                AND status = 'OK'
                AND refund_result_amount_minor IS NOT NULL
                AND refund_result_amount_minor > 0
                AND refund_fingerprint_version IS NOT NULL
                AND refund_fingerprint_version = 1
            WHEN refund_source_kind = 'LEGACY_ACTION' THEN
                action = 'REFUND'
                AND status = 'OK'
                AND refund_result_amount_minor IS NOT NULL
                AND refund_result_amount_minor > 0
                AND refund_fingerprint_version IS NULL
                AND refund_request_mode IS NULL
                AND refund_request_amount_minor IS NULL
            ELSE FALSE
        END
    );

ALTER TABLE payment_actions
    ADD CONSTRAINT payment_actions_typed_refund_terminal_check
    CHECK (
        CASE
            WHEN action = 'REFUND'
                AND refund_fingerprint_version IS NOT NULL
                AND status = 'OK'
                THEN refund_result_amount_minor IS NOT NULL
                    AND refund_result_amount_minor >= 0
                    AND (
                        (
                            refund_result_amount_minor = 0
                            AND refund_source_kind IS NULL
                        )
                        OR (
                            refund_result_amount_minor > 0
                            AND refund_source_kind = 'ATOMIC_ACTION'
                        )
                    )
            ELSE TRUE
        END
    );

ALTER TABLE payment_actions
    ADD CONSTRAINT payment_actions_refund_source_tuple_unique
    UNIQUE (id, booking_id, refund_source_kind, action, status, refund_result_amount_minor);

ALTER TABLE payments
    ADD CONSTRAINT payments_refund_source_tuple_unique
    UNIQUE (id, booking_id, status, amount_minor);

CREATE INDEX payments_booking_idx
    ON payments (booking_id);

CREATE TABLE booking_refund_reconciliation (
    booking_id UUID PRIMARY KEY,
    has_atomic_action_source BOOLEAN NOT NULL DEFAULT FALSE,
    has_legacy_action_source BOOLEAN NOT NULL DEFAULT FALSE,
    has_payment_status_source BOOLEAN NOT NULL DEFAULT FALSE,
    blocked_reason VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT booking_refund_reconciliation_reason_check
        CHECK (
            blocked_reason IS NULL
            OR blocked_reason IN (
                'MALFORMED_LEGACY_REFUND_ACTION',
                'INVALID_REFUNDED_PAYMENT_AMOUNT',
                'AMBIGUOUS_LEGACY_REFUND_SOURCES'
            )
        )
);

CREATE TABLE payment_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id UUID NOT NULL,
    source_kind VARCHAR(32) NOT NULL,
    action_id BIGINT,
    source_payment_id UUID,
    source_action TEXT,
    source_status TEXT NOT NULL,
    amount_minor BIGINT NOT NULL CHECK (amount_minor > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_refunds_source_shape_check
        CHECK ((
            (
                source_kind IN ('ATOMIC_ACTION', 'LEGACY_ACTION')
                AND action_id IS NOT NULL
                AND source_payment_id IS NULL
                AND source_action IS NOT NULL
                AND source_action = 'REFUND'
                AND source_status = 'OK'
            )
            OR (
                source_kind = 'PAYMENT_STATUS'
                AND action_id IS NULL
                AND source_payment_id IS NOT NULL
                AND source_action IS NULL
                AND source_status = 'REFUNDED'
            )
        ) IS TRUE),
    CONSTRAINT payment_refunds_action_source_fk
        FOREIGN KEY (
            action_id,
            booking_id,
            source_kind,
            source_action,
            source_status,
            amount_minor
        )
        REFERENCES payment_actions (
            id,
            booking_id,
            refund_source_kind,
            action,
            status,
            refund_result_amount_minor
        ),
    CONSTRAINT payment_refunds_payment_source_fk
        FOREIGN KEY (source_payment_id, booking_id, source_status, amount_minor)
        REFERENCES payments (id, booking_id, status, amount_minor)
);

CREATE UNIQUE INDEX payment_refunds_action_idx
    ON payment_refunds (action_id);

CREATE UNIQUE INDEX payment_refunds_source_payment_idx
    ON payment_refunds (source_payment_id);

CREATE INDEX payment_refunds_booking_idx
    ON payment_refunds (booking_id);

UPDATE payment_actions
SET refund_result_amount_minor = CAST(reason AS BIGINT),
    refund_source_kind = 'LEGACY_ACTION'
WHERE action = 'REFUND'
  AND status = 'OK'
  AND refund_fingerprint_version IS NULL
  AND refund_request_mode IS NULL
  AND refund_request_amount_minor IS NULL
  AND CASE
      WHEN reason ~ '^-?[0-9]{1,19}$'
          THEN CASE
              WHEN CAST(reason AS DECIMAL(20, 0)) <= 0 THEN FALSE
              ELSE CAST(reason AS DECIMAL(20, 0)) <= 9223372036854775807
          END
      ELSE FALSE
  END;

INSERT INTO payment_refunds (
    booking_id,
    source_kind,
    action_id,
    source_action,
    source_status,
    amount_minor,
    created_at
)
SELECT
    booking_id,
    'LEGACY_ACTION',
    id,
    'REFUND',
    'OK',
    refund_result_amount_minor,
    created_at
FROM payment_actions
WHERE refund_source_kind = 'LEGACY_ACTION'
  AND refund_result_amount_minor > 0;

INSERT INTO payment_refunds (
    booking_id,
    source_kind,
    source_payment_id,
    source_status,
    amount_minor,
    created_at
)
SELECT
    booking_id,
    'PAYMENT_STATUS',
    id,
    'REFUNDED',
    amount_minor,
    created_at
FROM payments
WHERE status = 'REFUNDED'
  AND booking_id IS NOT NULL
  AND amount_minor > 0;

INSERT INTO booking_refund_reconciliation (
    booking_id,
    has_atomic_action_source,
    has_legacy_action_source,
    has_payment_status_source,
    blocked_reason
)
SELECT
    booking_id,
    FALSE,
    MAX(has_legacy_action_source),
    MAX(has_payment_status_source),
    CASE
        WHEN MAX(has_malformed_action) THEN 'MALFORMED_LEGACY_REFUND_ACTION'
        WHEN MAX(has_invalid_payment) THEN 'INVALID_REFUNDED_PAYMENT_AMOUNT'
        WHEN MAX(has_legacy_action_source) AND MAX(has_payment_status_source)
            THEN 'AMBIGUOUS_LEGACY_REFUND_SOURCES'
        ELSE NULL
    END
FROM (
    SELECT
        booking_id,
        COALESCE(refund_source_kind = 'LEGACY_ACTION', FALSE) AS has_legacy_action_source,
        FALSE AS has_payment_status_source,
        action = 'REFUND'
            AND status = 'OK'
            AND refund_fingerprint_version IS NULL
            AND refund_request_mode IS NULL
            AND refund_request_amount_minor IS NULL
            AND refund_result_amount_minor IS NULL AS has_malformed_action,
        FALSE AS has_invalid_payment
    FROM payment_actions
    UNION ALL
    SELECT
        booking_id,
        FALSE,
        status = 'REFUNDED' AND amount_minor > 0,
        FALSE,
        status = 'REFUNDED' AND amount_minor <= 0
    FROM payments
    WHERE booking_id IS NOT NULL
) reconciliation_sources
GROUP BY booking_id;
