CREATE TABLE IF NOT EXISTS club_gamification_settings (
    club_id BIGINT PRIMARY KEY REFERENCES clubs(id),
    stamps_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    early_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    badges_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    prizes_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    contests_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    tables_loyalty_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    early_window_minutes INTEGER NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL REFERENCES clubs(id),
    code VARCHAR(255) NOT NULL,
    name_ru VARCHAR(255) NOT NULL,
    icon VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    condition_type TEXT NOT NULL,
    threshold INTEGER NOT NULL,
    window_days INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_badges_club_code UNIQUE (club_id, code)
);

CREATE TABLE IF NOT EXISTS user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL REFERENCES clubs(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    badge_id BIGINT NOT NULL REFERENCES badges(id),
    earned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    fingerprint TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_user_badges_fingerprint UNIQUE (fingerprint),
    CONSTRAINT uq_user_badges_club_user_badge UNIQUE (club_id, user_id, badge_id)
);

CREATE INDEX IF NOT EXISTS idx_user_badges_club_user
    ON user_badges (club_id, user_id);

CREATE TABLE IF NOT EXISTS prizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL REFERENCES clubs(id),
    code VARCHAR(255) NOT NULL,
    title_ru VARCHAR(255) NOT NULL,
    description CLOB,
    terms CLOB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    limit_total INTEGER,
    expires_in_days INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_prizes_club_code UNIQUE (club_id, code)
);

CREATE TABLE IF NOT EXISTS reward_ladder_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL REFERENCES clubs(id),
    metric_type TEXT NOT NULL,
    threshold INTEGER NOT NULL,
    window_days INTEGER,
    prize_id BIGINT NOT NULL REFERENCES prizes(id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    order_index INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_reward_ladder_levels UNIQUE (club_id, metric_type, threshold, window_days)
);

CREATE TABLE IF NOT EXISTS reward_coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL REFERENCES clubs(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    prize_id BIGINT NOT NULL REFERENCES prizes(id),
    status TEXT NOT NULL,
    reason_code TEXT,
    fingerprint TEXT NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    redeemed_at TIMESTAMP WITH TIME ZONE,
    issued_by BIGINT REFERENCES users(id),
    redeemed_by BIGINT REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_reward_coupons_fingerprint UNIQUE (fingerprint)
);

CREATE INDEX IF NOT EXISTS idx_reward_coupons_club_user_status
    ON reward_coupons (club_id, user_id, status);

CREATE INDEX IF NOT EXISTS idx_reward_coupons_club_status_issued
    ON reward_coupons (club_id, status, issued_at DESC);
